apiVersion: v1
kind: Secret
metadata:
  name: random-quotes-secrets
type: Opaque
stringData:
  homepageDisplay: "blah"

---
apiVersion: v1
kind: Secret
metadata:
  name: randomquotes-tls
data:
  tls.crt: abc
  tls.key: abc
type: kubernetes.io/tls

